name: Build Android Preview

on:
  push:
    branches: ['main', 'develop']
  workflow_dispatch:

jobs:
  build_android:
    name: Build Android Preview
    type: build
    params:
      platform: android
      profile: preview
